version: '3.9'
services:
  api-prospira-website:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MAIN_PKG: .           
    image: api-prospira-website:latest
    volumes:
      - ./uploads/resumes:/app/private/uploads/resumes:rw
      - ./uploads/appeals:/app/private/uploads/appeals:rw
      - ./uploads/images:/app/private/uploads/images:rw
    env_file:
      - .env    
    restart: always   
    environment:
      - DB_POSTGRES_USER=webapprove
      - DB_POSTGRES_PASSWORD=Psth@2024**
      - DB_POSTGRES_DB=prospira-website
      - DB_POSTGRES_HOST=10.144.1.104
      - DB_POSTGRES_PORT=5432
      - TOKEN_SECRET_KEY=1844cb55cd2b085135a1297c87196e46337b191710c96eadf2a2897e2b1cb8ce
      - SENDGRID_API_KEY=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
      - SMTP_HOST=10.145.0.250
      - SMTP_USERNAME=it-system@prospira-th.com
      - SMTP_PASSWORD=Psth@min135
      - SMTP_PORT=25
      - SMTP_SET_FROM=test-service@prospira.com
      - PORT=7777
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:7777/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks : 
      - prospira-website-network
  nginx-external-site:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api-prospira-website
    ports:
      - "7777:7777"
    restart: always
    networks:
      - prospira-website-network

volumes:
  prospira-website-volumn:
    driver: local
networks:
  prospira-website-network:
    driver: bridge