version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: prospira-db
    restart: always
    environment:
      POSTGRES_USER: prospira-dev
      POSTGRES_PASSWORD: prospira12345678
      POSTGRES_DB: prospira-dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
